name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Web
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false

      - name: Build Android APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean assembleDebug --info -Pandroid.incremental=false

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk BilharMontanhaeJukebox.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BilharMontanhaeJukebox-APK
          path: BilharMontanhaeJukebox.apk

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        with:
          tag_name: latest
          name: Versão Atualizada (APK)
          body: |
            Nova versão gerada automaticamente em ${{ github.event.head_commit.timestamp }}.
            Commmit: ${{ github.sha }}
            
            **Dica:** Baixe o arquivo `.apk` abaixo para instalar no seu Android.
          files: BilharMontanhaeJukebox.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
